name: Publish NPM Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@durolabs'

      - name: Install dependencies
        run: npm ci
      # TODO: run tests when nats is ready
      # - name: Run tests
      #   run: npm test

      - name: Determine version bump
        id: version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == *"version:major"* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ "$PR_TITLE" == *"version:minor"* ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version
        run: npm run version:${{ steps.version.outputs.bump }} --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Print NPM config
        run: |
          npm config list
          git status

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes
        run: git push origin HEAD:main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
